# docker compose -f docker-compose.yml up -d --build
version: '3'
services:
  vn_ldr_db:
    image: mysql:8
    container_name: vn_ldr_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vn_ldr_server
    restart: always
    networks:
      - vn_ldr_network

  vn_ldr_server:
    build:
      context: .
      target: development
    container_name: vn_ldr_server
    environment:
      DATABASE_URL: mysql://root:password@vn_ldr_db/vn_ldr_server?schema=public
      CRAWL_API_URL: https://example.com
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - vn_ldr_db
    networks:
      - vn_ldr_network

networks:
  vn_ldr_network:
    driver: bridge
