name: Build docker for dockerhub

on:
  push:
    branches:
      - 'main'
    paths: ['server/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            auth-service:
              - 'server/**'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push auth-service
        if: steps.filter.outputs.auth-service == 'true'
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:server'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vn_lda_server:latest
  pull:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vn_lda_server:latest
            docker run -d -p 3000:3000 --name vn_lda_server ${{ secrets.DOCKERHUB_USERNAME }}/vn_lda_server:latest
