name: Build docker for dockerhub

on:
  push:
    branches:
      - 'main'
    paths: ['server/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
              - 'server/**'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push server
        if: steps.filter.outputs.server == 'true'
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:server'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vn_ldr_server:latest
  pull:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull and run server docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vn_ldr_server:latest
            docker rm -f vn_ldr_server
            docker run -d --name vn_ldr_server -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e CRAWL_API_URL=${{ secrets.CRAWL_API_URL }} -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/vn_ldr_server:latest
